# Generated by Django 3.2.13 on 2022-11-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(default='없음'),
            preserve_default=False,
        ),
    ]
