# Generated by Django 3.2.13 on 2022-11-17 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('director', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('released_data', models.DateField()),
                ('overview', models.TextField()),
                ('posterpath', models.TextField()),
                ('genres', models.ManyToManyField(related_name='genre', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Genrescore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('users', models.ManyToManyField(related_name='genrescore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
