# Generated by Django 3.2.13 on 2022-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
