# Generated by Django 3.2.13 on 2022-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
